### ISSUE TITLE
none of the demos work?

### ISSUE THREAD

**Issue by ronaldjeremy** [CrackerakiUA/ngImgCropFullExtended#115]
In all of the demos, after uploading an image, there is a brief flash where the cropper and image is visible and then the canvas disappears.  The only thing left after that is the initial cropped image.

**Comment by CrackerakiUA** [comment]
i will checkout, i haven't made new release after accept new pulls. If you use latest release all should be good.

**Comment by CrackerakiUA** [comment]
people still using that crappy jquery and passed some of it on latest push. @TimoPerplex and @CedricEugeni please check the code you have added in PR and remove Jquery.

**Comment by CedricEugeni** [comment]
@CrackerakiUA : I didn't use Jquery in the code I produced.
Are you talking about the following line of code : 
`element.children(".loading").remove();`
I didn't do this line of code but if I look at the PR I did, there is this line added while I didn't do it.
If that is where the problem is coming from, how can I remove it ? Create another PR ?

**Comment by CrackerakiUA** [comment]
Yes, please create another PR.

**Comment by CrackerakiUA** [comment]
Looks fixed.

**Comment by TimoPerplex** [comment]
Hi, @CrackerakiUA, @CedricEugeni,

Pull request  #111 indeed introduced a jQuery dependency (my bad), but pull request #112 fixed that.

The bugfix of #111 and #112 has now been reverted which reintroduces the following bug:

When you select a bad file (xlsx, dll or anything that is not an image) the loading overlay shows. When you after this select a valid image, the image is shown with the loading overlay.

This is because there are now two loading overlays (the first one is not removed).
The pull request removes all loading children messages within the element thus fixing the problem stated above.

To reproduce:
1) Go to http://codepen.io/Crackeraki/pen/avYNKP
2) Select anything other than an image
3) Select a proper image
4) The loading overlay is still visible

**Comment by CedricEugeni** [comment]
Hi @TimoPerplex, it seems that PR #111 and PR #112 only modify source files and not generated files (maybe you forgot to do a `gulp build` before committing).

Can you fork from what is available on master right now and put your #112 fix again, then generate files using `gulp build`?

I think this will help @CrackerakiUA to put things back in order easily.

**Comment by TimoPerplex** [comment]
@CedricEugeni, @CrackerakiUA 

Done, i ran gulp build on the source and added a new pull request: #118.
Your revert #117 wasn't merged so didn't need to add the fix again.

**Comment by CedricEugeni** [comment]
Great @TimoPerplex ! :)
