### ISSUE TITLE
Size of the crop is much higher than of the original

### ISSUE THREAD

**Issue by karensg** [CrackerakiUA/ngImgCropFullExtended#45]
Hi,

Thanks a lot for your great library. Extremely useful.
I am wondering why the size of the cropped image is much bigger than of the original one.
Both images have the width of 1200px.

```
<img-crop image="picFile" change-on-fly="false" area-type="rectangle" area-min-size="{w: 1200, h:200}" chargement="'Afbeelding laden'" result-image-quality="0.9" result-image-format="picFile.type" result-image-size="{w:1200, h:450}" result-image="croppedDataUrl"></img-crop>
```

The original image:
https://s3-eu-west-1.amazonaws.com/pluggd-nl/public/artists/980191014/fotos/m6vfaKhXZa

The cropped image:
https://s3-eu-west-1.amazonaws.com/pluggd-nl/public/artists/980191014/fotos/m6vfaKhXZa_resize6rVHnWZKFS

Very strange...

Karens

**Comment by CrackerakiUA** [comment]
I will be active in 10 days. Meanwhile you can add codepen with options you used for those two images.

**Comment by mavrick** [comment]
@karensg from what I can see, the resized image is png and the original image is jpg.

You can confirm this in the response headers of the request.

See https://github.com/CrackerakiUA/ngImgCropFullExtended#result-image-format

The default output is `image/png`

**Comment by karensg** [comment]
How stupid of me. I copied it from another page where the crop is done with a blob. This one uses the url to the image. Thanks a lot, @mavrick

**Comment by mitomm** [comment]
Just in case anyone else is dealing with the same issue and still gets bigger results images (compared to the original one), make sure to use  `result-image-format=" 'image/jpeg' "` with an `'` around `image/jpeg`. I'm not sure what is really going on here, since the result image will be jpeg in both cases, however it will only work properly with the single quote  `'`  around `'image/jpeg'`.
Spend hours to figuring this out. Maybe this saves someone else the hassle.
