### ISSUE TITLE
White screen when I was trying to upload an image. Why do I get it? Here is my code.

### ISSUE THREAD

**Issue by developandbehappy** [CrackerakiUA/ngImgCropFullExtended#99]
I'm using ng-file-upload for upload image, and getting white screen. 
JS

``` js
angular.module('someApp', [
  'ngFileUpload',
  'ngImgCrop'
]);
```

``` html
 <link rel="stylesheet" type="text/css" href="ng-img-crop.css">
<script src="angular.min.js"></script>
<script src="ng-img-crop.js"></script>

<div ng-if="fileUpload" class="diary">
        <div class="diary-crop-image" style="height: {{ dataImageForCrop.height + 'px' }};">
            <img-crop image="fileUpload | ngfDataUrl" area-type="rectangle" result-image="diaryParams.thumb"></img-crop>
        </div>
    </div>
<div ng-show="!fileUpload && !diaryData.thumb">
        <div type="file" ng-model="fileUpload" ngf-drop="uploadFiles($file, $invalidFiles)"
             ngf-select="uploadFiles($file, $invalidFiles)"
             ngf-validate="fileValidateProps"
             class="diary-upload bordered">
            <div class="upload-picture">
                <div class="upload-button"></div>
                <p class="text-center">
                    Чтобы загрузить, нажмите на иконку картинки<br>
                    или перетащите файл в это окно
                </p>
            </div>
        </div>
    </div>
```

I'm just trying to upload an image, I can see it, but later it disappears. What is the problem?

video with problem: https://youtu.be/L2oKqh03bGM

**Comment by CrackerakiUA** [comment]
can you reproduce it inside codepen?

**Comment by developandbehappy** [comment]
I've already found a solution to my problem. The problem was in angular, I don't know why but using ng-if causes such a flicker. Native library doesn't have it. We need to check it. So thank you, the issue can be closed

**Comment by thierryskoda** [comment]
@zidein07 I had exactly the same problem haha! It should be written : USE `ng-show` in the README 😄

**Comment by CrackerakiUA** [comment]
If you have issues with `ng-if` and `ng-show` start use objects. Example

``` Javascript
$scope.imageHandler = {
  fileUpload: false,
  src: 'some src to the img',
  dest: 'dataUrl result'
}
```

``` html
<div ng-if="imageHandler.fileUpload" class="diary">
  <img-crop image="imageHandler.src | ngfDataUrl" area-type="rectangle" result-image="imageHandler.dest"></img-crop
</div>
```

and i believe you will never have that problem. Some people use controller as object which solve the issue also but it's ugly by my option. This all happens because `ng-if` create it's own scope, you can also see issue like that in the `ng-repeat` where object is solution also. `ng-if` is way better solution, i almost never use `ng-show`, it has bad performance because in almost every case you don't have to create the DOM, which `ng-show` do. `ng-show` should be used only for css scripting where you need to get some height or width of hidden object or DOM elemenets which got hidden pretty rare or for small period of time.
